apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: microservices-gcp-ticketing
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: sg-k8s-testing
  artifacts:
    - image: arrigolupori/auth
      # us.gcr.io/sg-k8s-testing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: arrigolupori/tickets
      # us.gcr.io/sg-k8s-testing/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: arrigolupori/orders
      # us.gcr.io/sg-k8s-testing/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: arrigolupori/client
      # us.gcr.io/sg-k8s-testing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.{js,jsx}"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
