apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: microservices-gcp-ticketing
build:
  local:
    push: false
  artifacts:
    - image: arrigolupori/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**.ts'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*